### ISSUE TITLE
Features: Clear programmatically

### ISSUE THREAD

**Issue by Psycarlo** [pakenfit/react-native-pin-input#10]
A feature where you could call a function and the pin input clears itself would be awesome

**Comment by pakenfit** [comment]
Hi @Psycarlo thanks for the feature request, I will implement this asap

**Comment by Psycarlo** [comment]
Awesome 🔥

**Comment by pakenfit** [comment]
@Psycarlo  Is this the feature you're looking for ?

https://github.com/pakenfit/react-native-pin-input/assets/27218088/ebf2ca83-e350-4a4d-b7e4-695e2151bbf1

**Comment by Psycarlo** [comment]
@pakenfit yes. amazing! you rock

**Comment by Psycarlo** [comment]
Are you going to release 1.4.0? 🚀

**Comment by pakenfit** [comment]
@Psycarlo Yes just released it, could you try and tell me if it is okay please ?

**Comment by Psycarlo** [comment]
@pakenfit it's good!
